### ISSUE TITLE
IE8 error

### ISSUE THREAD

**Issue by drakeman** [emilkm/amfjs#10]
does it work for IE8 ?? coz im trying to implement the client for ie8 and it kept giving me error :
"uint8array undefined"
and then i try to use polyfill typedarray js and now it give me this error : 
"invalid argument amf.js line 201"
its on the "this.send(new Uint8Array(xmlhttpRequest.message));"

**Comment by emilkm** [comment]
Sorry, will not look at old browsers support. My time would be better spent on improving what I have and adding documentation.
