### ISSUE TITLE
Don't understand the example

### ISSUE THREAD

**Issue by marcusfritze** [emilkm/amfjs#11]
Hi,

actually I don't understand the example. 
```
var amfClient = new amf.Client("amfphp", "http://127.0.0.1/server/gateway.php");
        amfClient.invoke("test", "ping", [],
            function(data) {
                console.log(data);
            },
            function(data) {
                console.log("ping errror");
            }
        );
```

What is the amfphp in this example? Is this the folder where the test.php class file is located? What should I type when I want to use a class file in a sub-sub directory?

So in this example the test.php file is located in the Services folder of the amfphp?

**Comment by emilkm** [comment]
Hi,

The first parameter is the destination. Amfphp does not really make use of the destination, but a BlazeDS might.

Yes, the service file is in the services folder. You can use "subfolder.test" to invoke a service in the services/subfolder/test.php of the services folder. "sub.sub.test" for a service in services/sub/sub/test.php

Are you using original Amfphp 1.9, or the Silexlabs 2.X? If you intend to work with a PHP server, then I might suggest looking at my https://github.com/emilkm/efxphp project. You can use the https://github.com/emilkm/efxphp-bootplate get going faster. If you are running on a server where you can load custom extensions you can use https://github.com/emilkm/amfext

I am in the process of documenting efxphp, and porting amfext to PHP 7 (that may take some time), and then I may look at updating amfjs. 

Tell me a bit more about your project, I might be able to help.

Cheers

**Comment by marcusfritze** [comment]
Thank you for your quick and informative answer.

I have a Apache Flex project with amfphp 2.0 and PHP classes / functions as a "backend".

So I tried to use Angular and your amfjs to connect to my existing amfphp backend. Because I want to use the existing PHP backend with the new Angular frontend.

But when I try to connect with your amfjs to my amfphp backend I get:

PHP Notice:  Undefined property: stdClass::$messageId in /var/www/html/<mydomain>/www/amfphp/Plugins/AmfphpFlexMessaging/AmfphpFlexMessaging.php on line 127

in my php logs and

Object {faultCode: 2, faultDetail: "", faultString: "Unknown Error."}
test.service.ts?d232:45 ping errror

in my javascript console.

Does this amfjs not work with amfphp 2.X? It's a little bit hard to understand the efxphp without any documentation. ;-)

I am looking just for the possibility to use and to connect to my existing php classes / function in my angular / javascript.

**Comment by marcusfritze** [comment]
when I add

        if (this.sendMessageId) {
            message.messageId = amf.uuid(0, 0);
        }

to the line 159 in the amf.js file, the PHP Notice goes away

**Comment by emilkm** [comment]
I am glad you found the solution. The initial idea of the library was to send the bare minimum data working with a custom version of the old amfphp. That made it problematic for some working with other server implementations. I will add this to the library. 

Thanks
