### ISSUE TITLE
Issue with ArrayCollection

### ISSUE THREAD

**Issue by overmont** [emilkm/amfjs#12]
Hi,

I'm running into an issue when I request an AMF service that returns an ArrayCollection. Should be an array with 2 columns : Code, Libelle.

Here is what I get : The first object is OK but the others are split into an Object and a label ! See print screen for details.

![image](https://cloud.githubusercontent.com/assets/4212860/16480345/e97d8524-3ea5-11e6-9067-341ed2c74c70.png)

Could you please tel me if I'm doing something wrong or if something could be done to solve this issue ?

Thanks in advance,

Olivier

**Comment by emilkm** [comment]
Hi, 

Can you provide a small snippet of a sample ArrayCollection that I can use to try and replicate the issue?

You can of course try passing an Array instead.

**Comment by overmont** [comment]
Hi,

Here is the raw response I get from the server, I hope it will help you (see file).
[getListeMetiers - Response.txt](https://github.com/emilkm/amfjs/files/345804/getListeMetiers.-.Response.txt)

I'm working on a HTML5 frontend, I don't manage the backend so I can't change from ArrayCollection to Array.

Regards,

Olivier

**Comment by overmont** [comment]
Hi,

Is the file I uploaded of any help ? Do you need anything else ?

Regards.

**Comment by emilkm** [comment]
Hi,

Thanks for the file. I will look at the issue this weekend.

The conversion of amfext to PHP 7 is eating a lot of time at the moment. Plus I have documentation to do for efxphp, etc. amfjs is a bit on of a lower priority at the moment, but I will see if I can figure it out.

Cheers

**Comment by emilkm** [comment]
I just tried reading the file with the efxphp input reader and it couldn't  read the AMF packet. That is pretty well tested and is used in production so it should be working. I will try and run it through the BlazeDS Java reader just to double check.

Maybe you can capture a whole request response with Charles debugging proxy and send me a saved session. If Charles could read the AMF packet then it is a good indication it is fine.

**Comment by emilkm** [comment]
Issue with reading traits fixed.
