### ISSUE TITLE
Any examples on how to login and subscribe to blazeds topics? 

### ISSUE THREAD

**Issue by mycroft11** [emilkm/amfjs#15]

**Comment by emilkm** [comment]
The library does not support the JMS Publish-and-subscribe mode of operation out of the box. 

I do not work with BlazeDS and do not have examples handy. Some of the users of the library have indicated that they are using it with BlazeDS.

If you can pick your server and you don't mind trying some PHP, I can help you to get going with https://github.com/emilkm/efxphp
