### ISSUE TITLE
BlazeDS return DSK instead of AcknowledgeMessage

### ISSUE THREAD

**Issue by dsworldtrip** [emilkm/amfjs#6]
Hi I am trying to use your JS library to send and receive AS3 Objects.  It works well but only when BlazeDS (3.5) returns AcknowledgeMessage messages that it can deserialize, if Blaze returns the Object as a DSK it chokes (all properties are present). The problem is BlazeDS is not being consistent on the type it returns for any given method, sometimes DSK sometimes AcknowledgeMessage (for the same method call, at some point during its up time it decides to return AcknowledgeMessage). The flex application handles this no problem, but how can I force Blaze to respond correctly OR get the Lib to deserialize a DSK correctly?

**Comment by DCSDB** [comment]
Also try turning of small messages in the BLAZEDS channel as per:

https://stackoverflow.com/questions/25530481/blazeds-return-dsk-instead-of-acknowledgemessage

`<properties>
				 <serialization>
				  <enable-small-messages>false</enable-small-messages>
				 </serialization>
			</properties>
`
