### ISSUE TITLE
Can not properly display Chinese characters content

### ISSUE THREAD

**Issue by oxiao** [emilkm/amfjs#9]
when i used it to show some Chinese characters content, it's fault in page. but i can find correct result of amf data by HTTP spying. May some issues in functions writeUTF and readUTF??

**Comment by emilkm** [comment]
Hi, 

Can you provide a minimal example that would help replicate the issue. Which implementation are you using on the server side?

**Comment by emilkm** [comment]
UTF read/write fixed
